// Auto-generated by Figma → Storybook pipeline
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { DesignAIv10 } from './DesignAIv10.tsx';

const meta = {
  title: 'UI Screens/DesignAIv10',
  component: DesignAIv10,
  parameters: { layout: 'fullscreen' },
  tags: ['autodocs'],
} satisfies Meta<typeof DesignAIv10>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    userName: 'David',
    userFullName: 'David Levi',
    userPlan: 'Portfolio ID: 20144874',
    activeNavId: 'dashboard',
  },
};
