import React from "react"
import { BadgeAvatar } from "./BadgeAvatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BadgeAvatar,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=18%3A616",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      dot: figma.boolean("dot"),
      fill: figma.enum("fill", {
        yes: "yes",
        no: "no",
      }),
      // No matching props could be found for these Figma properties:
      // "dot": figma.boolean('dot')
    },
    example: (props) => <BadgeAvatar dot={props.dot} fill={props.fill} />,
  },
)
