import React from "react"
import { CardKpi } from "./CardKpi"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CardKpi,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=19-396&t=VTc5uMKDtwwNHV2h-4",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("card title"),
      kpiLabel: figma.string("kpi title ✏️"),
      kpiValue: figma.string("kpi num ✏️")
      // No matching props could be found for these Figma properties:
      // "num": figma.string('num'),
      // "text": figma.string('text')
    },
    example: (props) => <CardKpi title={props.title} kpiLabel={props.kpiLabel} kpiValue={props.kpiValue} />,
  },
)
