import React from "react"
import { ButtonIcon } from "./ButtonIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonIcon,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=21%3A5481",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      state: figma.enum("state", {
        idle: "idle",
        hover: "hover",
        foucs: "focus",
        disabled: "disabled",
      }),
    },
    example: (props) => <ButtonIcon state={props.state} />,
  },
)
