import React from "react"
import { SearchBar } from "./SearchBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SearchBar,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=17%3A814",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      state: figma.enum("state", {
        idle: "idle",
        focused: "focused",
        disabled: "disabled",
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text ✏️'),
      // "size": figma.enum('size', {
      //   "s": "s"
      // }),
      // "type": figma.enum('type', {
      //   "empty": "empty",
      //   "filled": "filled"
      // })
    },
    example: (props) => <SearchBar state={props.state} />,
  },
)
