import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=18%3A1539",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("label ✏️"),
      state: figma.enum("state", {
        idle: "idle",
        hover: "hover",
        focus: "focus",
        disabled: "disabled",
      }),
      leftIcon: figma.instance("icon L ↩️"),
      rightIcon: figma.instance("icon R ↩️"),
      // No matching props could be found for these Figma properties:
      // "lIcon": figma.boolean('L icon'),
      // "rIcon": figma.boolean('R icon'),
      // "label": figma.string('label ✏️'),
      // "iconL": figma.instance('icon L ↩️'),
      // "iconR": figma.instance('icon R ↩️')
    },
    example: (props) => (
      <Button
        label={props.label}
        state={props.state}
        leftIcon={props.leftIcon}
        rightIcon={props.rightIcon}
      />
    ),
  },
)
