const COMPONENTS_ROOT = process.env.COMPONENTS_ROOT || 'src/components';

export function buildPrompt(
  figmaUrl: string,
  nodeId: string,
  componentName: string,
): string {
  const storyPath = `${COMPONENTS_ROOT}/${componentName}/${componentName}.stories.tsx`;

  return `You are working inside the Storybook project at the current directory.

1. Read the Figma component at ${figmaUrl} (node ${nodeId}) using the Figma MCP.
2. Scan ${COMPONENTS_ROOT}/ to find all existing components and their exported props/types.
3. Map the Figma component's name and variants to the best-matching existing component(s).
4. Write a Storybook CSF3 story file at ${storyPath}.

Rules:
- Import ONLY from existing components found in step 2. Do not create new components.
- Derive args exclusively from the real TypeScript prop types of the matched component.
- Cover every variant documented in the Figma component properties.
- If no matching component exists, write the story with a prominent TODO comment and leave the import path as \`// TODO: import { ${componentName} } from '...'\`.
- Add the file header: // Auto-generated by Figma → Storybook pipeline. Review before merging.
- Use CSF3 format with TypeScript.
- Import Meta and StoryObj from '@storybook/react-vite'.
- Include \`tags: ['autodocs']\` in the meta.
- One named export per Figma variant (PascalCase).
- No inline styles — use component props only.`;
}
