import React from "react"
import { CardInsuranceCoverage } from "./CardInsuranceCoverage"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardInsuranceCoverage,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=23%3A681",
  {
    props: {},
    example: (props) => <CardInsuranceCoverage />,
  },
)
