import React from "react"
import { Tag } from "./Tag"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=309%3A1686",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      showChevron: figma.boolean("chevron"),
      icon: figma.instance("icon"),
      label: figma.string("text ✏️"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text ✏️'),
      // "icon": figma.instance('icon'),
      // "chevron": figma.boolean('chevron'),
      // "state": figma.enum('state', {
      //   "Idle": "idle",
      //   "hover": "hover",
      //   "active": "active",
      //   "disabled": "disabled",
      //   "focused": "focused"
      // })
    },
    example: (props) => (
      <Tag
        label={props.label}
        showChevron={props.showChevron}
        icon={props.icon}
      />
    ),
  },
)
