import React from "react"
import { AvatarUser } from "./AvatarUser"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarUser,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=30%3A1270",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      active: figma.boolean("active"),
      src: figma.string("text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('text')
    },
    example: (props) => <AvatarUser active={props.active} src={props.src} />,
  },
)
