import React from "react"
import { SummaryItem } from "./SummaryItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SummaryItem,
  "https://www.figma.com/design/7LWL1TZvifdDf8Oz2AH1tZ/AI-Demo-design?node-id=18%3A1404",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("title ✏️"),
      kpi: figma.string("kpi ✏️"),
      description: figma.string("description ✏️"),
      showDescription: figma.boolean("description2"),
      // No matching props could be found for these Figma properties:
      // "title": figma.string('title ✏️'),
      // "kpi": figma.string('kpi ✏️'),
      // "description": figma.string('description ✏️'),
      // "description2": figma.boolean('description2')
    },
    example: (props) => (
      <SummaryItem
        title={props.title}
        kpi={props.kpi}
        description={props.description}
        showDescription={props.showDescription}
      />
    ),
  },
)
